# Generated by Django 5.0.7 on 2024-08-11 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('second_name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, max_length=255)),
                ('orderItems', models.JSONField(default=dict)),
                ('orderPrice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('paymentType', models.CharField(max_length=60)),
                ('paid_status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
