# Generated by Django 5.0.7 on 2024-08-06 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extra_Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=70)),
                ('img_url', models.URLField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='ProductName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveSmallIntegerField()),
                ('grams', models.PositiveBigIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.productname')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('Pizzas', 'Pizzas'), ('Snacks', 'Snacks'), ('Beverages', 'Beverages'), ('Cocktails', 'Cocktails'), ('Cofe', 'Cofe'), ('Desserts', 'Desserts'), ('Sauces', 'Sauces')], max_length=50)),
                ('img_url', models.URLField()),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=4)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('extra_info', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(blank=True)),
                ('extra_ingredients', models.ManyToManyField(blank=True, to='products.extra_ingredients')),
                ('ingredients', models.ManyToManyField(blank=True, to='products.ingredients')),
                ('name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.productname')),
                ('sizes', models.ManyToManyField(to='products.sizes')),
            ],
        ),
    ]
