# Generated by Django 5.0.7 on 2024-08-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizes',
            name='size',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
