# Generated by Django 5.0.7 on 2024-08-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_sizes_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizes',
            name='grams',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
