# Generated by Django 5.0.7 on 2024-08-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_sizes_grams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
