# Generated by Django 5.0.7 on 2024-08-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_ingredients_ingredient_ingredients_img_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='ingredients', to='products.ingredients'),
        ),
    ]
