# Generated by Django 5.0.7 on 2024-08-15 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='extra_ingredients',
        ),
        migrations.DeleteModel(
            name='Extra_Ingredients',
        ),
    ]
