# Generated by Django 5.0.7 on 2024-08-15 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_options'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
